### PR TITLE
Migrate swf config

### LINKED ISSUE #20: Bring base configuration used in the uds-package-software-factory into this repo
We want to move gitlabs configuration that is currently used at the [uds-package-software-factory](https://github.com/defenseunicorns/uds-package-software-factory) level to this repository.

We then want to provide a way for the capability to accept a values overlay.yaml file for additional configuration if necessary by the package that is importing this capability.

Acceptance Criteria:
- [ ] This gitlab capability now has a default configuration that mirrors what [uds-package-software-factory](https://github.com/defenseunicorns/uds-package-software-factory) is using.
- [ ] Makefile is updated to satisfy the dependencies it will need to for testing with the new configuration

### PR DESCRIPTION
**Pull request by anthonywendt**
Closes #20

### CODE REVIEW

**Comment by anthonywendt** [comment]
Still need to update README. Will take care of it in the morning

**Comment by corang** [comment]
Why is the gitlab database name a variable? I think it would be better to make it static.

**Comment by anthonywendt** [comment]
> Why is the gitlab database name a variable? I think it would be better to make it static.

To allow the database names to be configured if needed. The RDS folks had issues with what we had hard coded before because they couldn't have hyphens in the dbname. So I made it configurable and default to a new name without hyphens at the software factory level. Didn't know if there would be any other weird limitations to different provisioned databases that may need to be able to configure a name that works for them.

**Review by corang — DISMISSED** [review]

**Pull request merged**
